# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: vFields
email: lingchen_yu@126.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.vfields.com" # the base hostname & protocol for your site
host: "vfields.com" # the base hostname
author: wait

# Gems
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
paginate: 6
paginate_path: 'page:num/'
comments: true
excerpt_separator: <!-- more -->

# Recent posts num
recent_posts_num: 10

#评论信息
duoshuo:
  config: true
  id: vfields