# Where things are
source:       .
destination:  ./_site
layouts:      ./_layouts
paginate:     5

# Handling Reading
safe:         true
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:    kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

# Markdown Processors
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#站点基础配置
title: vFields
subTitle: Another Boring Blog.
description: wait 的博客
# local
#url: http://127.0.0.1:4000
url:  http://www.vfields.com
feed: /atom.xml

categories_path : /categories.html

#菜单配置
nav:
  - text: 首页
    url: /index.html
  - text: 文章
    url: /archives.html
  - text: 目录
    url: /categories.html

#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /themes/violet/images/hdbg01.jpg

#评论信息
disqus:
  config: true
  id: vfields
duoshuo:
  config: false
  id: 
